name: Basic Sanity Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Run tests
        run: |
          # Create Python 3.10 compatibility patch
          cat > patch_collections.py << EOF
          #!/usr/bin/env python3
          import collections
          import collections.abc
          
          # Apply the patches for all needed classes
          collections.Mapping = collections.abc.Mapping
          collections.Sequence = collections.abc.Sequence
          print("Patches applied: collections.Mapping and collections.Sequence")
          EOF
          
          # Create a simple test runner
          cat > run_tests.py << EOF
          import collections
          import collections.abc
          import sys
          import importlib.util
          
          # Import the patch
          spec = importlib.util.spec_from_file_location("patch_collections", "patch_collections.py")
          patch = importlib.util.module_from_spec(spec)
          spec.loader.exec_module(patch)
          
          # Run pytest
          import pytest
          sys.exit(pytest.main(["tests/"]))
          EOF
          
          # Run the tests
          python run_tests.py 